version: '3'

tasks:
  doc:rfc:
    desc: render the RFC note
    cmds:
      - ls *.md | entr -c glow RFC-6749.md
  api:gen:
    desc: generate type from openapi spec
    cmds:
      - oapi-codegen --config=api/oapi-codegen.yaml api/openapi.yaml
  build:
    desc: build the project
    cmds:
      - go build -o bin/oauth2-server cmd/main.go
  test:
    desc: run tests
    cmds:
      - go test ./...
  test:v:
    desc: run tests with verbose output
    cmds:
      - go test -v ./...
